hosts:
  # core routers
  cr1-eqiad.wikimedia.org:
    template: cr
    site: eqiad
    data:
       mgmt_ip: [ 10.65.0.12/16, 10.65.0.13/16 ]

  cr2-eqiad.wikimedia.org:
    template: cr
    site: eqiad
    data:
       mgmt_ip: [ 10.65.0.14/16, 10.65.0.15/16 ]

  cr1-eqord.wikimedia.org:
    template: cr
    site: eqord
    data:
       mgmt_ip: [ 10.193.0.60/16 ]
       mgmt_gw: 10.193.0.1

  cr1-codfw.wikimedia.org:
    template: cr
    site: codfw
    data:
       mgmt_ip: [ 10.193.0.10/16, 10.193.0.11/16 ]

  cr2-codfw.wikimedia.org:
    template: cr
    site: codfw
    data:
       mgmt_ip: [ 10.193.0.12/16, 10.193.0.13/16 ]

  cr1-eqdfw.wikimedia.org:
    template: cr
    site: eqdfw
    data:
       mgmt_ip: [ 10.193.0.61/16 ]
       mgmt_gw: 10.193.0.1

  cr1-ulsfo.wikimedia.org:
    template: cr
    site: ulsfo
    data:
       mgmt_ip: [ 10.128.128.2/17 ]

  cr2-ulsfo.wikimedia.org:
    template: cr
    site: ulsfo
    data:
       mgmt_ip: [ 10.128.128.3/17 ]

  cr1-esams.wikimedia.org:
    template: cr
    site: esams
    data:
       mgmt_ip: [ 10.21.0.116/24 ]

  cr2-knams.wikimedia.org:
    template: cr
    site: esams

  cr2-knams.wikimedia.org:
    template: cr
    site: esams

  # peering switches
  psw1-eqiad.mgmt.eqiad.wmnet:
    template: generic
    site: eqiad

  psw2-eqiad.mgmt.eqiad.wmnet:
    template: generic
    site: eqiad

  # management switches/routers
  mr1-eqiad.wikimedia.org:
    template: mr
    site: eqiad

  msw1-eqiad.mgmt.eqiad.wmnet:
    template: msw
    site: eqiad

  mr1-ulsfo.wikimedia.org:
    template: mr
    site: ulsfo

  mr1-esams.wikimedia.org:
    template: mr
    site: esams

commondata:
    asn: 14907
    lvs:
      - 10.2.1.0/24
      - 10.2.2.0/24
      - 10.2.3.0/24
      - 10.2.4.0/24
      - 91.198.174.192/27
      - 198.35.26.96/27
      - 208.80.153.224/27
      - 208.80.154.224/27
    lvs6:
      - 2620:0:860:ed1a::/64
      - 2620:0:861:ed1a::/64
      - 2620:0:862:ed1a::/64
      - 2620:0:863:ed1a::/64

sitedata:
    eqiad:
       confed: 65001
       mgmt_gw: 10.65.0.1
       customers:
         - 64700 # fundraising-eqiad
       bgp_out:
         - 208.80.152.0/22
         - 208.80.154.0/23
       bgp6_out:
         - 2620:0:860::/46
       lvs_secondary:
         - 208.80.154.137
         - 208.80.154.138
         - 208.80.154.139
    eqord:
       confed: 65001
       bgp_out:
         - 208.80.152.0/22
       bgp6_out:
         - 2620:0:860::/46
    codfw:
       confed: 65002
       mgmt_gw: 10.193.0.1
       customers:
         - 64701 # fundraising-codfw
       bgp_out:
         #- 208.80.152.0/22
         - 208.80.152.0/23
       bgp6_out:
         #- 2620:0:860::/46
         - 2620:0:860::/48
       lvs_secondary:
         - 10.192.17.4
         - 10.192.17.5
         - 10.192.17.6
    eqdfw:
       confed: 65002
       bgp_out:
         #- 208.80.152.0/22
         - 208.80.152.0/23
       bgp6_out:
         #- 2620:0:860::/46
         - 2620:0:860::/48
    ulsfo:
       confed: 65004
       mgmt_gw: 10.128.128.1
       customers:
         - 11820 # WMF HQ
       bgp_out:
         - 198.35.26.0/23
       bgp6_out:
         - 2620:0:863::/48
       lvs_secondary:
         - 10.128.0.13
         - 10.128.0.14
    esams:
       asn: 43821
       confed:
       mgmt_gw: 10.21.0.1
       bgp_out:
         - 91.198.174.0/24
         - 185.15.56.0/22
       bgp6_out:
         - 2620:0:862::/48
         - 2a02:ec80::/32
       lvs:
         - 10.2.0.0/16
         - 91.198.174.192/27
         - 91.198.174.224/28
       lvs6:
         - 2620:0:862:ed1a::/64
       lvs_secondary:
         - 10.20.0.13
         - 10.20.0.14
