---
cr1-eqiad.wikimedia.org:
  role: cr
  site: eqiad
  config:
    mgmt_ip: [10.65.0.12/16, 10.65.0.13/16]
    fpcs_to_sample: [4]

cr2-eqiad.wikimedia.org:
  role: cr
  site: eqiad
  config:
    mgmt_ip: [10.65.0.14/16, 10.65.0.15/16]
    fpcs_to_sample: [3]

cr2-eqord.wikimedia.org:
  role: cr
  site: eqord
  config:
    fpcs_to_sample: [0]

cr1-codfw.wikimedia.org:
  role: cr
  site: codfw
  config:
    mgmt_ip: [10.193.0.10/16, 10.193.0.11/16]
    fpcs_to_sample: [5]

cr2-codfw.wikimedia.org:
  role: cr
  site: codfw
  config:
    mgmt_ip: [10.193.0.12/16, 10.193.0.13/16]
    fpcs_to_sample: [5]

cr2-eqdfw.wikimedia.org:
  role: cr
  site: eqdfw
  config:
    fpcs_to_sample: [0]

cr3-ulsfo.wikimedia.org:
  role: cr
  site: ulsfo
  config:
    mgmt_junos: true  # Separate mgmt interface in special routing instance
    fpcs_to_sample: [0]

cr4-ulsfo.wikimedia.org:
  role: cr
  site: ulsfo
  config:
    mgmt_junos: true  # Separate mgmt interface in special routing instance
    fpcs_to_sample: [0]

cr3-esams.wikimedia.org:
  role: cr
  site: esams
  config:
    mgmt_ip: [10.21.0.119/24, 10.21.0.120/24]
    fpcs_to_sample: [0]

cr2-esams.wikimedia.org:
  role: cr
  site: esams
  config:
    mgmt_ip: [10.21.0.117/24, 10.21.0.118/24]
    fpcs_to_sample: [0]

cr3-knams.wikimedia.org:
  role: cr
  site: knams
  config:
    fpcs_to_sample: [0]

cr1-eqsin.wikimedia.org:
  role: cr
  site: eqsin
  config:
    mgmt_ip: [10.132.128.2/17, 10.132.128.3/17]
    # TODO: on the MX104 sampling settings are part of the 'AFEB' rather than an FPC

cr2-eqsin.wikimedia.org:
  role: cr
  site: eqsin
  config:
    mgmt_junos: true  # Separate mgmt interface in special routing instance
    fpcs_to_sample: [0]

# access switches
asw2-a-eqiad.mgmt.eqiad.wmnet:
  role: asw
  site: eqiad
  config:
    lldp_disabled: ['ge-8/0/10']

asw2-b-eqiad.mgmt.eqiad.wmnet:
  role: asw
  site: eqiad
  config:
    igmp_snooping: false  # T201039

asw2-c-eqiad.mgmt.eqiad.wmnet:
  role: asw
  site: eqiad
  config:
    igmp_snooping: false  # T201039

asw2-d-eqiad.mgmt.eqiad.wmnet:
  role: asw
  site: eqiad
  config:
    igmp_snooping: false  # T201039

asw-a-codfw.mgmt.codfw.wmnet:
  role: asw
  site: codfw
  config:
    lldp_disabled: ['ge-1/0/47']  # SRXs show L2 errors when receiving LLDP frames

asw-b-codfw.mgmt.codfw.wmnet:
  role: asw
  site: codfw

asw-c-codfw.mgmt.codfw.wmnet:
  role: asw
  site: codfw

asw-d-codfw.mgmt.codfw.wmnet:
  role: asw
  site: codfw

asw2-esams.mgmt.esams.wmnet:
  role: asw
  site: esams
  config:
    lldp_disabled: ['ge-5/0/47']  # SRXs show L2 errors when receiving LLDP frames

asw2-ulsfo.mgmt.ulsfo.wmnet:
  role: asw
  site: ulsfo
  config:
    lldp_disabled: ['ge-1/0/13']  # SRXs show L2 errors when receiving LLDP frames

asw1-eqsin.mgmt.eqsin.wmnet:
  role: asw
  site: eqsin
  config:
    lldp_disabled: ['ge-0/0/23']  # SRXs show L2 errors when receiving LLDP frames

# management switches/routers
mr1-eqiad.wikimedia.org:
  role: mr
  site: eqiad
  config:
    security_zones:
      - name: production
        services: ['ssh', 'ping', 'traceroute', 'snmp', 'ospf', 'ospf3']
        interfaces: ['lo0.0', 'ge-0/0/1.401', 'ge-0/0/1.402']
      - name: untrust
        services: ['ssh', 'ping', 'traceroute']
        interfaces: ['ge-0/0/5.0']
      - name: mgmt
        services: ['ssh', 'ping', 'traceroute']
        interfaces: ['ge-0/0/0.0']
      - name: access
        services: ['ssh', 'ping', 'traceroute', 'dhcp']
        interfaces: ['ge-0/0/2.0']
    dhcp_pool: 10.66.0.0/24

msw1-eqiad.mgmt.eqiad.wmnet:
  role: msw
  site: eqiad

mr1-codfw.wikimedia.org:
  role: mr
  site: codfw
  config:
    security_zones:
      - name: production
        services: ['ssh', 'ping', 'traceroute', 'snmp', 'ospf', 'ospf3']
        interfaces: ['lo0.0', 'ge-0/0/1.401', 'ge-0/0/1.402']
      - name: untrust
        services: ['ssh', 'ping', 'traceroute']
        interfaces: ['ge-0/0/7']
      - name: mgmt
        services: ['ssh', 'ping', 'traceroute']
        interfaces: ['ge-0/0/0.0']
      - name: access
        services: ['ssh', 'ping', 'traceroute', 'dhcp']
        interfaces: ['ge-0/0/2']

mr1-eqsin.wikimedia.org:
  role: mr
  site: eqsin

msw1-codfw.mgmt.codfw.wmnet:
  role: msw
  site: codfw
  config:
    lldp_disabled: ['ge-0/0/32']  # SRXs show L2 errors when receiving LLDP frames

mr1-ulsfo.wikimedia.org:
  role: mr
  site: ulsfo

mr1-esams.wikimedia.org:
  role: mr
  site: esams
  config:
    security_zones:
      - name: production
        services: ['ssh', 'ping', 'traceroute', 'snmp', 'ospf', 'ospf3']
        interfaces: ['lo0.0', 'ge-0/0/1.402', 'ge-0/0/1.404']
      - name: untrust
        services: ['ssh', 'ping', 'traceroute']
        interfaces: ['ge-0/0/6.2484']
      - name: mgmt
        services: ['ssh', 'ping', 'traceroute']
        interfaces: ['irb.900']
      - name: access
        services: ['ssh', 'ping', 'traceroute', 'dhcp']
        interfaces: ['ge-0/0/2.0']
      - name: customers
        services: ['ping', 'traceroute']
        interfaces: ['ge-0/0/6.2483']
        screen: untrust-screen

# payments firewall
# pfw-eqiad.wikimedia.org:
#   role: pfw
#   site: eqiad

# pfw-codfw.wikimedia.org:
#   role: pfw
#   site: codfw
